import Head from 'next/head';
import Image from 'next/image';
import { Inter, Road_Rage } from 'next/font/google';
// import styles from '@/styles/Home.module.css';
import NavBar from '@/layout/NavBar';
import Footer from '@/layout/Footer';
import Hero from '@/components/Home/Hero';
import OurTeam from '@/components/Home/OurTeam';
import About from '@/components/Home/About';
import Features from '@/components/Home/Features';
import Tokenomics from '@/components/Home/Tokenomics';
import Roadmap from '@/components/Home/Roadmap';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Hero />
			<About />
			<Features />
			<Tokenomics />
			<OurTeam />
		</>
	);
}
