import Holdings from '@/components/Dashboard/Holdings';
import Head from 'next/head';

export default function Dashboard() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<section className='relative w-full'>
				<div className=' absolute bg-[url("/section_svg/earth-globe.svg")]' />

				<div className='w-full flex flex-col gap-[128px] px-[176px] py-[148px] md:flex-row'>
					<div className='w-full max-w-[493px] flex-col items-start md:items-center'>
						<h1 className='text-white text-[80px] leading-[87px] font-ruberoid font-extrabold mb-4'>
							Omniapp Dashboard
						</h1>

						<p className='text-white text-[32px] leading-[47px] font-ruberoid font-normal mb-4'>
							Connect your wallet to check your holdings.
						</p>

						<p className='text-white text-[22px] leading-[27px] font-inter font-bold'>
							Note: $OMP tokens will be avaliable for claim once presale has finished.
						</p>
						<div className='w-full flex items-center space-x-[35px] mt-[56px]'>
							<button className='flex flex-row items-center justify-center py-4 px-[46px] gap-[10px] bg-plain rounded-lg'>
								<span className='text-white hover:text-main text-[16px] font-ruberoid font-semibold leading-[23px]'>
									Connect Wallet
								</span>
							</button>
						</div>
					</div>
					<div className='w-full max-w-[585px]'>
						<Holdings />
					</div>
				</div>
			</section>
		</>
	);
}
